### ISSUE TITLE
Sibling matching does not appear to work

### ISSUE THREAD

**Issue by Fleker** [phenomnomnominal/tsquery#29]
I've been playing around with the [TSQuery Playground](https://tsquery-playground.firebaseapp.com/) and have been running into some difficulty trying to match sibling nodes, which does not seem to be working.

For example:

```
function f(n:any){
  return n+n;
}
```

Trying a query for `Identifier[name='n']` finds matches, as does `Identifier[name='n'], AnyKeyword`. In the tree, I can see the variable name and type are listed as siblings. However, a query like `Identifier[name='n'] + AnyKeyword` does not match.

The same issue comes up with expressions like `console.log`, which has two Identifier sibling nodes, but I cannot seem to find a way to match this expression with a valid query.

![image](https://user-images.githubusercontent.com/3291635/46560422-8e2a5500-c8a8-11e8-8f2c-6c7144a9ae09.png)

**Comment by phenomnomnominal** [comment]
Looks like you're right, and looks like I don't have tests for this either! I'll have a go at fixing this!

**Comment by phenomnomnominal** [comment]
Had a bit of a dig, and it looks like it is possible - the issue is that TSQuery Playground doesn't support the `visitAllChildren` option. Even with that flag turned on, it's still a bit tricky. The `+` operator is specifically for the very next sibling, where as the `~` operator works on any subsequent sibling. I wrote some more tests that will hopefully demonstrate this: https://github.com/phenomnomnominal/tsquery/blob/master/test/sibling.spec.ts#L24

Let me know if that makes sense?

**Comment by Fleker** [comment]
That does make sense, although I did not realize that there needed to be an additional option enabled to allow for this kind of traversal.

**Comment by Fleker** [comment]
Is there an existing issue to follow with regards to enabling this feature in the playground?
