### ISSUE TITLE
Question: how to find PropertyAccessExpression with two identifiers?

### ISSUE THREAD

**Issue by yosiat** [phenomnomnominal/tsquery#83]
Hi,

This library is super-awesome! I am using it together with `ts-morph` and I am trying to write a query and can't get it fetch a results.

```typescript
const enum A {
	B,
	C
}

const obj = {
	target: A.B 
}
```

This is a simplified example of what I am trying to achieve, I want to write a query that will fetch me all `ObjectLiteralExpression` with property of `target` that equals to some string (in this case `A.B`).

Now I managed to write a query to fetch ObjectLiteralExpression with key of "target", but I struggle to do the value part.

According to https://tsquery-playground.firebaseapp.com/ what I should look for is:
* PropertyAccessExpression
  * Identifier[name="A"]
  * Identifier[name="B"] 

If I understand ts-query correctly, I should look for (in simple way) `Identifier[name="A"] + Identifier[name="B"]` but this query yields no results.

I inspected the tree with some recursion I wrote and I see the tree is a bit different, it contains an Identifier, followed by a DotToken followed by an Identifier. I changed the query to match it - `Identifier[name="A"] + DotToken + Identifier[name="B"]` and still no results.

So, my first question is: what I am doing wrong here?
My second question, is it possible to write a query like "give me PropertyAssignment when right side have text of 'A.B'" ?

Thanks,
Yosi

**Comment by phenomnomnominal** [comment]
Hey Yosi! 

So the first answer is that there are different ways to recurse the tree. Things like `DotToken`s are _concrete_ parts of the syntax (rather than _abstract_), TSQuery operates on the **abstract** part of the tree so it doesn't know about specific characters in the syntax like `.` or `[` or whatever.

The tsquery playground thing doesn't really give a full picture of what's going on. It is often easier to use astexplorer.net in TypeScript mode, which will show more detail of the AST. Using that, we can see that a `PropertyAccessExpression` has two components, the `expression` and the `name`, where `expression` is the left hand side of the `.` and  `name` is the right hand side of the `.`. In your case you're looking for `expression` to be an `Identifier` with name `"A"` and `name` to be an `Identifier` with name `"B"`, so your full query should be:

`PropertyAccessExpression[expression.name=A][name.name=B]`

Another way you could write this would be `PropertyAccessExpression:has(Identifier[name=A]):has(Identifier[name=B])`, but this query will still succeed if it was `B.A` because it isn't specific about which `Identifier` is which!

Hopefully that kind of makes sense?

**Comment by phenomnomnominal** [comment]
Well the answer is _kind of_. Whatever "XXX" is isn't a syntactic construct, so an AST query isn't going to match it. If "XXX" is constant, then just figure out what the query for it is and use that. If you need to generate it programatically somehow then it's a bit harder. You can always search for all instances of `PropertyAssignment:has([name="target"])` and then use the complete set of matches to find the line + col position in the source text, and then search for "XXX" after it, but that could be a bit sketchy?

**Comment by yosiat** [comment]
@phenomnomnominal gotcha, this what I thought.. because ts-query is allowing me to do structural query and what I am asking is not structural question.

Was trying to see if I can make my code-generation code less coupled to the structure of the code (if we move from enum to simple string or something else), but it's kinda make sense now that I think about it that it will be coupled to it.

Thanks a lot!
