### ISSUE TITLE
:function selector is missing method declared in module export 

### ISSUE THREAD

**Issue by KrishnaPG** [phenomnomnominal/tsquery#85]
The `:function` selector is missing the methods declared directly in the module.exports. For example, in the code below the `fn1` is not detected
```
module.exports = {
  fn1(a, b) {  // <<-- this is not detected
    return a + b;
  },
  fn2: function (a, b) {
    return a + b;
  },
  fn3: (a,b) => a+b
}
```

**Comment by phenomnomnominal** [comment]
So that's an interesting one. I believe `:function` specifically selects `FunctionDeclaration`, `FunctionExpression`, `ArrowFunction` etc etc, but that particular construct is a `MethodDeclaration`. I'm not sure what would be less surprising here... adding it to the `:function` selector would definitely be a breaking change though 🤔

**Comment by phenomnomnominal** [comment]
Added in v6
